// Copyright 2026 Stefan Prodan.
// SPDX-License-Identifier: Apache-2.0
//
// One Sample per second, as /api/snapshot and the socket carry it.

import type { DiskDir } from "./host.ts";
import type { ModelInfo } from "./models.ts";
import type { InFlight, LastRequest } from "./requests.ts";

export type Sample = {
  t: number; // unix ms
  engineUp: boolean;
  epoch: number; // bumps when the engine's counters go backwards (restart)
  windowMs: number | null; // length of the window the rates cover
  decodeTps: number | null;
  prefillTps: number | null;
  requestsRunning: number;
  requestsWaiting: number;
  requestsPrefilling: number;
  // what the running requests have done so far: prompt tokens forwarded by
  // the in-flight prefill, tokens generated by in-flight decodes
  prefillTokensLive: number;
  inflightTokens: number;
  phaseSince: number | null; // unix ms the current phase began (sampler)
  // the engine-wide request in flight and the last one that finished
  request: InFlight | null;
  lastRequest: LastRequest | null;
  cacheHitPct: number | null; // hits / queries over the window
  cacheTokenPct: number | null; // cached prompt tokens / prompt tokens, windowed
  ttftMs: number | null; // mean TTFT of requests that finished in the window
  ttftN: number; // how many requests that mean covers
  gpuPct: number;
  generatedTokens: number; // lifetime counter (this epoch)
  promptTokens: number; // lifetime prompt tokens, cached or not (this epoch)
  cachedPromptTokens: number; // of those, restored from the prefix cache
  requestsTotal: number; // lifetime successful requests (this epoch)
  requestsCancelled: number; // lifetime cancelled requests (this epoch)
  enginePid: number | null; // only when the engine runs on this host
  engineStartedAt: number | null; // unix ms, from the process table (local)
  engineCpuPct: number | null; // percent of one core over the last tick (local)
  mem: {
    hostTotal: number;
    hostFree: number;
    hostInactive: number;
    hostWired: number;
    hostCompressed: number;
    // engine process: libproc rusage when the pid is known, else what the
    // engine reports about itself (memory_mb)
    procFootprint: number;
    procRss: number; // 0 when the pid is unknown
    weights: number; // sum of bytesResident over loaded models
    hotCacheEst: number; // max(0, mlxActive - weights); no gauge exists yet
    mlxActive: number;
    mlxPool: number;
  };
  disk: DiskDir[]; // cache tier directories, refreshed every 30 s
  models: ModelInfo[];
};
